# Generated by Django 4.0.4 on 2022-04-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_customerproducthistory_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerproducthistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
